### ISSUE TITLE
not sure how to download

### ISSUE THREAD

**Issue by PanCake1714** [MrUnknown11/SFS-ThrustMod#3]
I'm simply not sure how to download it, I used to have it but I've forgoten, or it's changed, can anyone help?

**Comment by MrUnknown11** [comment]
It's not compatible with the newest version if SFS PC. So, it will not work properly if you download it. SFS has it's own modloader. But in my mod's latests version has 3th party modloader. As I said earlier it will not work with the newest version of the game.Sent from Android deviceOn Aug 2, 2023 00:15, PanCake1714 ***@***.***> wrote:
I'm simply not sure how to download it, I used to have it but I've forgoten, or it's changed, can anyone help?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

On Aug 2, 2023 00:15, PanCake1714 ***@***.***> wrote:
I'm simply not sure how to download it, I used to have it but I've forgoten, or it's changed, can anyone help?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

On Aug 2, 2023 00:15, PanCake1714 ***@***.***> wrote:
I'm simply not sure how to download it, I used to have it but I've forgoten, or it's changed, can anyone help?
